severity: warning

linters:
  StringQuotes:
    enabled: true
    style: double_quotes
  HexNotation:
    enabled: true
    style: lowercase

  # Disabled since we want to order by attribute type, not by alphabet
  PropertySortOrder:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  VendorPrefix:
    enabled: false

  NestingDepth:
    enabled: false

  SelectorDepth:
    enabled: false

  SelectorFormat:
    convention: hyphenated_BEM

  NameFormat:
    enabled: false

  LeadingZero:
    enabled: true
    style: include_zero
