severity: warning

scss_files: 'app/assets/stylesheets/*'

linters:
  StringQuotes:
    enabled: true
    style: double_quotes
  HexNotation:
    enabled: true
    style: lowercase

  # Disabled since we want to order by attribute type, not by alphabet
  PropertySortOrder:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  VendorPrefix:
    enabled: false

  NestingDepth:
    enabled: false

  SelectorDepth:
    enabled: false

  SelectorFormat:
    convention: hyphenated_BEM

  NameFormat:
    enabled: false

  LeadingZero:
    enabled: true
    style: include_zero

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%', 'fr']                               # Other

  PropertySpelling:
    enabled: false
