# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 161793a2a7e8efdcf3723a55f5b03d5de38108b4d2333f60b261e7f562be2b9227c4675871ef3b01165a69329085841f7bd912b17091114fd7488d108ca57232

test:
  secret_key_base: 548271b967e7f5a515e61481d58232885b1d940119a3f52240c2e93e16edaedb1b9f4a1eb041f04d44368f2a52a504126d38f6cb1ac3acc5443e7614345adfd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
